services:
  redis:
    container_name: cache
    image: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
